### ISSUE TITLE
Error while installing the RBDL python wrapper 

### ISSUE THREAD

**Issue by Prathamesh-Saraf** [ORB-HD/rbdl-orb#65]
No extra python directory is generated in the build directory after doing: 
$ cmake -D CMAKE_BUILD_TYPE=Release RBDL_BUILD_PYTHON_WRAPPER=ON ../

**Comment by ju6ge** [comment]
when using cmake and specifying multiple options via the cmd each needs to be prefixed by -D … 

so what you need is:
```cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_PYTHON_WRAPPER=ON ..```

**Comment by Prathamesh-Saraf** [comment]
Thank you @ju6ge! the command worked. Although, after I added: 
export PYTHONPATH=$PYTHONPATH:<rbdl-build/python>/python
to my bash file, I am not able to source it. It says "bash: /python: Permission denied"

**Comment by Prathamesh-Saraf** [comment]
Thanks a lot @ju6ge ! it is working now
