### ISSUE TITLE
Python error in CalcCenterOfMass

### ISSUE THREAD

**Issue by antoinedelplace** [ORB-HD/rbdl-orb#71]
Hi !

There seems to be a Python error at this level because of qddot (if statement followed by numpy array) :
- [https://github.com/ORB-HD/rbdl-orb/blob/08faa1d262c25f06373c333da00da61d6f78e03c/python/rbdl-wrapper.pyx#L2346](https://github.com/ORB-HD/rbdl-orb/blob/08faa1d262c25f06373c333da00da61d6f78e03c/python/rbdl-wrapper.pyx#L2346)
- [https://github.com/ORB-HD/rbdl-orb/blob/08faa1d262c25f06373c333da00da61d6f78e03c/python/rbdl-wrapper.pyx#L2352](https://github.com/ORB-HD/rbdl-orb/blob/08faa1d262c25f06373c333da00da61d6f78e03c/python/rbdl-wrapper.pyx#L2352)

Python error is :
```
File "rbdl.pyx", line 3150, in rbdl.CalcCenterOfMass
if qddot and com_acceleration is not None: 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()```

**Comment by ju6ge** [comment]
close with #72
