### ISSUE TITLE
fatal error: optional: No such file or directory

### ISSUE THREAD

**Issue by MisterJunwei** [ORB-HD/rbdl-orb#81]
cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_PYTHON_WRAPPER=ON  -D RBDL_BUILD_ADDON_URDFREADER=ON ..
make -j8

【fatal error】optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.

**Comment by ju6ge** [comment]
This issue tells me very little about the system and compiler you are using. 

My guess would be that your compiler is very old and does not support C++17, which has an optional type that is used by the urdf addon.

Kind regards,
Felix
