### ISSUE TITLE
URDF reading angle convention discrepenancy

### ISSUE THREAD

**Issue by PeterQLee** [ORB-HD/rbdl-orb#88]
Hello,

I noticed that there appears to be a discrepancy in the order of operations when the Spatial Transform matrix is built from reading URDF files.  In https://github.com/ORB-HD/rbdl-orb/blob/321e20e80e2859a3a2ab43629c7c26c1020cb6f6/addons/urdfreader/urdfreader.cc#L249-L253 it appears that the euler joint angle order is in ZYX. However, this contradicts documentation (http://wiki.ros.org/urdf/XML/joint) that indicates the order as XYZ. 

It should be noted that back in commit 4e36ba8a0fb9b68b45c25ad0fe40fc261bb3f351 the reader used the XYZ order, which leads me to believe that there was a regression when the URDF reader code was revamped. 

I've prepared a small patch for this, unless further discussion is necessary.

**Comment by ju6ge** [comment]
Closed with #89.
