### ISSUE TITLE
meshup command error: Error opening animation file output/meshup.csv

### ISSUE THREAD

**Issue by wangchangys** [ORB-HD/rbdl-orb#90]
**Hi,there.
 I have tested the example constrainedDoublePendulum. I build the program successfully, in build folder i run :
./constrainedDoublePendulumForwardDynamics
it gives the right results:**

==============================
1. Forward Dynamics 
==============================
Columns
      t,        ke,       pe,    ke+pe ,norm(cons_pos), norm(cons_vel)
0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000
0.030000, 0.074239, -0.074239, 0.000000, 0.000000, 0.000000
0.060000, 0.296914, -0.296914, 0.000000, 0.000000, 0.000000
0.090000, 0.667669, -0.667669, 0.000000, 0.000000, 0.000000
0.120000, 1.185130, -1.185130, 0.000000, 0.000000, 0.000000
0.150000, 1.845890, -1.845890, -0.000000, 0.000000, 0.000000
0.180000, 2.643470, -2.643470, -0.000000, 0.000000, 0.000000
0.210000, 3.567814, -3.567814, -0.000000, 0.000000, 0.000000
0.240000, 4.605609, -4.605608, 0.000000, 0.000000, 0.000000
0.270000, 5.741238, -5.741238, 0.000000, 0.000000, 0.000000
0.300000, 6.957738, -6.957738, 0.000000, 0.000000, 0.000000
0.330000, 8.237324, -8.237324, -0.000000, 0.000000, 0.000000
0.360000, 9.561525, -9.561525, -0.000000, 0.000000, 0.000000
0.390000, 10.911164, -10.911164, -0.000000, 0.000000, 0.000000
0.420000, 12.266282, -12.266282, -0.000000, 0.000000, 0.000000
0.450000, 13.605772, -13.605772, -0.000000, 0.000000, 0.000000
0.480000, 14.905985, -14.905985, -0.000000, 0.000000, 0.000000
0.510000, 16.136976, -16.136976, 0.000000, 0.000000, 0.000000
0.540000, 17.254754, -17.254753, 0.000001, 0.000000, 0.000000
0.570000, 18.190859, -18.190859, 0.000000, 0.000000, 0.000000
0.600000, 18.857995, -18.857993, 0.000002, 0.000000, 0.000000
0.630000, 19.207403, -19.207401, 0.000002, 0.000000, 0.000000
0.660000, 19.277718, -19.277717, 0.000002, 0.000000, 0.000000
0.690000, 19.139624, -19.139622, 0.000002, 0.000000, 0.000000
0.720000, 18.838033, -18.838030, 0.000003, 0.000000, 0.000000
0.750000, 18.388297, -18.388294, 0.000003, 0.000000, 0.000000
0.780000, 17.788048, -17.788045, 0.000003, 0.000000, 0.000000
0.810000, 17.025660, -17.025657, 0.000003, 0.000000, 0.000000
0.840000, 16.084710, -16.084708, 0.000002, 0.000000, 0.000000
0.870000, 14.949799, -14.949797, 0.000002, 0.000000, 0.000000
0.900000, 13.622800, -13.622797, 0.000003, 0.000000, 0.000000
0.930000, 12.147238, -12.147234, 0.000004, 0.000000, 0.000000
0.960000, 10.606298, -10.606295, 0.000003, 0.000000, 0.000000
0.990000, 9.084459, -9.084456, 0.000003, 0.000000, 0.000000
1.020000, 7.641065, -7.641062, 0.000003, 0.000000, 0.000000
1.050000, 6.311035, -6.311032, 0.000003, 0.000000, 0.000000
1.080000, 5.113535, -5.113532, 0.000003, 0.000000, 0.000000
1.110000, 4.058634, -4.058631, 0.000003, 0.000000, 0.000000
1.140000, 3.151293, -3.151290, 0.000003, 0.000000, 0.000000
1.170000, 2.393708, -2.393705, 0.000003, 0.000000, 0.000000
1.200000, 1.786738, -1.786735, 0.000003, 0.000000, 0.000000
1.230000, 1.330730, -1.330727, 0.000003, 0.000000, 0.000000
1.260000, 1.025803, -1.025800, 0.000003, 0.000000, 0.000000
1.290000, 0.871439, -0.871436, 0.000003, 0.000000, 0.000000
1.320000, 0.865295, -0.865292, 0.000003, 0.000000, 0.000000
1.350000, 1.001860, -1.001857, 0.000003, 0.000000, 0.000000
1.380000, 1.272625, -1.272622, 0.000003, 0.000000, 0.000000
1.410000, 1.668330, -1.668327, 0.000003, 0.000000, 0.000000
1.440000, 2.181119, -2.181116, 0.000003, 0.000000, 0.000000
1.470000, 2.804822, -2.804819, 0.000003, 0.000000, 0.000000
1.500000, 3.533948, -3.533944, 0.000003, 0.000000, 0.000000
1.530000, 4.362465, -4.362462, 0.000003, 0.000000, 0.000000
1.560000, 5.282786, -5.282783, 0.000003, 0.000000, 0.000000
1.590000, 6.284982, -6.284979, 0.000003, 0.000000, 0.000000
1.620000, 7.356270, -7.356267, 0.000003, 0.000000, 0.000000
1.650000, 8.480957, -8.480954, 0.000003, 0.000000, 0.000000
1.680000, 9.641140, -9.641137, 0.000003, 0.000000, 0.000000
1.710000, 10.818474, -10.818471, 0.000003, 0.000000, 0.000000
1.740000, 11.996927, -11.996924, 0.000003, 0.000000, 0.000000
1.770000, 13.165750, -13.165747, 0.000003, 0.000000, 0.000000
1.800000, 14.321085, -14.321082, 0.000003, 0.000000, 0.000000
1.830000, 15.464395, -15.464392, 0.000003, 0.000000, 0.000000
1.860000, 16.596183, -16.596180, 0.000003, 0.000000, 0.000000
1.890000, 17.702499, -17.702494, 0.000005, 0.000000, 0.000000
1.920000, 18.723762, -18.723747, 0.000015, 0.000000, 0.000001
1.950000, 19.468539, -19.468529, 0.000010, 0.000000, 0.000001
1.980000, 19.539562, -19.539539, 0.000022, 0.000000, 0.000001
2.010000, 18.905439, -18.905418, 0.000022, 0.000000, 0.000001
2.040000, 17.967975, -17.967946, 0.000029, 0.000000, 0.000000
2.070000, 16.937479, -16.937448, 0.000031, 0.000001, 0.000001
2.100000, 15.878826, -15.878795, 0.000031, 0.000001, 0.000001
2.130000, 14.806040, -14.806009, 0.000031, 0.000001, 0.000001
2.160000, 13.716756, -13.716724, 0.000031, 0.000001, 0.000000
2.190000, 12.607048, -12.607016, 0.000032, 0.000001, 0.000000
2.220000, 11.478540, -11.478508, 0.000032, 0.000001, 0.000000
2.250000, 10.340412, -10.340380, 0.000032, 0.000001, 0.000000
2.280000, 9.207819, -9.207787, 0.000032, 0.000001, 0.000000
2.310000, 8.098674, -8.098643, 0.000032, 0.000001, 0.000000
2.340000, 7.030552, -7.030521, 0.000032, 0.000001, 0.000000
2.370000, 6.018643, -6.018611, 0.000032, 0.000001, 0.000000
2.400000, 5.074870, -5.074838, 0.000032, 0.000001, 0.000000
2.430000, 4.207921, -4.207888, 0.000032, 0.000001, 0.000000
2.460000, 3.424007, -3.423975, 0.000032, 0.000001, 0.000000
2.490000, 2.728595, -2.728562, 0.000032, 0.000001, 0.000001
2.520000, 2.129654, -2.129621, 0.000033, 0.000001, 0.000001
2.550000, 1.641499, -1.641466, 0.000033, 0.000001, 0.000001
2.580000, 1.283740, -1.283707, 0.000033, 0.000001, 0.000001
2.610000, 1.072645, -1.072611, 0.000033, 0.000001, 0.000000
2.640000, 1.015398, -1.015365, 0.000033, 0.000001, 0.000000
2.670000, 1.112701, -1.112667, 0.000033, 0.000001, 0.000000
2.700000, 1.363109, -1.363076, 0.000033, 0.000001, 0.000000
2.730000, 1.765295, -1.765261, 0.000033, 0.000001, 0.000000
2.760000, 2.318670, -2.318636, 0.000033, 0.000001, 0.000000
2.790000, 3.023257, -3.023224, 0.000033, 0.000001, 0.000000
2.820000, 3.879209, -3.879176, 0.000033, 0.000001, 0.000000
2.850000, 4.886072, -4.886039, 0.000033, 0.000001, 0.000000
2.880000, 6.041792, -6.041758, 0.000033, 0.000001, 0.000000
2.910000, 7.341343, -7.341309, 0.000034, 0.000001, 0.000000
2.940000, 8.774690, -8.774656, 0.000034, 0.000001, 0.000000
2.970000, 10.323193, -10.323159, 0.000034, 0.000001, 0.000000
3.000000, 11.951996, -11.951961, 0.000035, 0.000001, 0.000000
Columns
      t,        ke,       pe,    ke+pe ,norm(cons_pos), norm(cons_vel)
Wrote: ../output/meshup.csv (meshup animation file)
Wrote: ../output/simulationData.csv (error data)

**However, when i used the meshup command in the constrainedDoublePendulum folder :**
`~/Documents/rbdl-orb/examples/constrainedDoublePendulum$ meshup model/constrainedDoublePendulum.lua output/meshup.csv`
**the result was:**
```

Reading settings from file:  /home/wang/.meshup/settings.json
Using GLEW     :  1.7.0
OpenGL Version :  4.1 (Compatibility Profile) Mesa 21.2.6
GLSL Version   :  4.10
Load model model/constrainedDoublePendulum.lua
Loading mesh /usr/local/share/meshup/meshes/unit_cube.obj
Error opening animation file output/meshup.csv!

```

**Actually, the output folder did not exist in the constrainedDoublePendulum folder, I dont know why?**
**what's more, i also tried sudo ./constrainedDoublePendulumForwardDynamics, but the" output" folder did not show as well**

**Comment by ju6ge** [comment]
Meshup is deprecated, use rbdl-toolkin instead!
