### ISSUE TITLE
Rbdl installation problem

### ISSUE THREAD

**Issue by tianbaoloin** [ORB-HD/rbdl-orb#93]
Python binding has not been successful，The current software is python3 version， cython3 python3-numpy python3-scipy python3-matplotlib has been installed，when i execute this command（cmake -D CMAKE_BUILD_TYPE=Release ../rbdl -D RBDL_BUILD_PYTHON_WRAPPER=ON），The terminal prompt is as follows：
**_(base) tian@tian:~/Documents/rbdl-build$ cmake -D CMAKE_BUILD_TYPE=Release ../rbdl -D RBDL_BUILD_PYTHON_WRAPPER=ON
-- Found NumPy: /home/tian/miniconda3/lib/python3.9/site-packages/numpy/core/include (found version "1.21.5")
-- Found PythonInterp: python3 (found version "3.9.5")
-- Found Cython: /usr/bin/cython3  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.10")
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tian/Documents/rbdl-build_**
Then the python folder was generated in the rbdl-build folder，I added the path to the python folder,（export PYTHONPATH=$PYTHONPATH:/home/tian/Documents/rbdl-build/python） but import rbdl still reports an error，
I don't know where is the problem,Maybe the question I asked is relatively simple, I am still a newbie in rbdl and cmake.Looking forward to your reply

**Comment by ju6ge** [comment]
cmake only generates the build files for rbdl, to actually build the software you also have to run `make` in your build folder!

**Comment by tianbaoloin** [comment]
> cmake only generates the build files for rbdl, to actually build the software you also have to run `make` in your build folder!
I just ran the command sudo make install, then rebooted and it works for now, thanks for your prompt reply.

**Comment by ju6ge** [comment]
No problem ;)
