### ISSUE TITLE
Use urdf addon

### ISSUE THREAD

**Issue by Yefkghcs** [ORB-HD/rbdl-orb#97]
hi, when I try to use urdf addon:
`cmake -D RBDL_BUILD_ADDON_URDFREADER=ON ../`

it shows an error:
```
CMake Error at addons/urdfreader/thirdparty/CMakeLists.txt:3 (MESSAGE):
  The urdfreader module was not initalized correctly! Please make sure that
  you recursively cloned rbdl.  For more information take a closer look at
  the README!


-- Configuring incomplete, errors occurred!
```
so I go to check the CMakeLIsts.txt, 
```
FIND_FILE(URDF_MODULE CMakeLists.txt PATHS ${CMAKE_CURRENT_SOURCE_DIR}/urdfparser NO_DEFAULT_PATH)
IF (URDF_MODULE STREQUAL URDF_MODULE-NOTFOUND)
  MESSAGE(FATAL_ERROR "The urdfreader module was not initalized correctly! Please make sure that you recursively cloned rbdl. For more information take a closer look at the README!")
ENDIF(URDF_MODULE STREQUAL URDF_MODULE-NOTFOUND)
ADD_SUBDIRECTORY(
	urdfparser
)
```
probably because the path of the file was not found? 
and what do you mean that "You will need to have cloned the repository recursively!", is there any file I need to copy to the URDF folder

**Comment by ju6ge** [comment]
This is the second time I see this issue (#95) and it is entirely preventable if you actually read the error message to completion! It tells you to take a look at the README of this repository. Some code like the URDF-Reader code is included as a seperate repository. Using git submodules allows keeping the URDF-Parser code in a seperate repository which allows it to be used standalone from RBDL.

# Relevant lines in the README:

## Building RBDL from Source

The official rbdl-orb git repository can be cloned from
```
    https://github.com/ORB-HD/rbdl-orb
```

(See [https://git-scm.com/downloads/guis/](https://git-scm.com/downloads/guis/) for git clients.)

To make sure all submodules are correctly downloaded, clone the repository recursively!

```
git clone --recursive https://github.com/ORB-HD/rbdl-orb
```

## Upgrading from an older version of RBDL

For convenience there is a script to upgrade to the newest RBDL repository version.

```
./upgrade.sh
```

It pulls the latest commits from master and also checks out the correct version of all sub repositories. Manual upgrading requires doing the following:

```
git pull origin master
git submodule update --init
```
